### ISSUE TITLE
Comillas dobles

### ISSUE THREAD

**Issue by MrJako2001** [zkreations/blogger-syntax#1]
¡Hola!, gracias por tan maravillosa herramienta,
¿hay alguna posibilidad que al generar las etiquetas se pueda cambiar de comillas simples a comillas dobles?

**Comment by danieIabel** [comment]
Buenos dias amigo. Lo recomendable es usar comillas simples, ya que en Blogger los atributos siempre se cambian a estas debido a que las expresiones pueden contener string u otro tipo de datos que requieran comillas dobles, en consecuencias tendrias error al guardar. ¿Tiene alguna razón por la que desea comillas dobles?

**Comment by MrJako2001** [comment]
Nada en especial, gracias por la información.
Que tengas un buen día.
